<?php

namespace ContainerKkGMi6x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DSQ8JltService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dSQ8Jlt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dSQ8Jlt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'request' => ['privates', '.errored..FvvW2V', NULL, 'Cannot determine controller argument for "App\\Controller\\IdentificationController::new()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'request' => '?',
        ]);
    }
}
