<?php

namespace ContainerOnEmAOO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OvL9SuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OvL_9Su' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OvL_9Su'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IdentificationController::acceuil' => ['privates', '.service_locator.XsktmwC', 'get_ServiceLocator_XsktmwCService', true],
            'App\\Controller\\IdentificationController::identification' => ['privates', '.service_locator.Mw9PxsK', 'get_ServiceLocator_Mw9PxsKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\IdentificationController:acceuil' => ['privates', '.service_locator.XsktmwC', 'get_ServiceLocator_XsktmwCService', true],
            'App\\Controller\\IdentificationController:identification' => ['privates', '.service_locator.Mw9PxsK', 'get_ServiceLocator_Mw9PxsKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\IdentificationController::acceuil' => '?',
            'App\\Controller\\IdentificationController::identification' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\IdentificationController:acceuil' => '?',
            'App\\Controller\\IdentificationController:identification' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
