<?php

namespace Container3SaA4FT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IWznQNMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iWznQNM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iWznQNM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IdentificationController::identification' => ['privates', '.service_locator.Mw9PxsK', 'get_ServiceLocator_Mw9PxsKService', true],
            'App\\Controller\\IdentificationController::test' => ['privates', '.service_locator.8FaX6n5', 'get_ServiceLocator_8FaX6n5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\IdentificationController:identification' => ['privates', '.service_locator.Mw9PxsK', 'get_ServiceLocator_Mw9PxsKService', true],
            'App\\Controller\\IdentificationController:test' => ['privates', '.service_locator.8FaX6n5', 'get_ServiceLocator_8FaX6n5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\IdentificationController::identification' => '?',
            'App\\Controller\\IdentificationController::test' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\IdentificationController:identification' => '?',
            'App\\Controller\\IdentificationController:test' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
