<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV01bB2W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV01bB2W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV01bB2W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV01bB2W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV01bB2W\App_KernelDevDebugContainer([
    'container.build_hash' => 'V01bB2W',
    'container.build_id' => '1fd1f085',
    'container.build_time' => 1675625789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV01bB2W');
