<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3SaA4FT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3SaA4FT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3SaA4FT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3SaA4FT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3SaA4FT\App_KernelDevDebugContainer([
    'container.build_hash' => '3SaA4FT',
    'container.build_id' => '89e7df2c',
    'container.build_time' => 1674726190,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3SaA4FT');
